spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:postgresql://planeja-postgres:5432/planeja
    driver-class-name: org.postgresql.Driver
    username: planeja
    password: planeja123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: false

app:
  jwt:
    secret: TyBzb2wgw6kgYW1hcmVsbw==
    expiration-seconds: 3600
